import '../models/models.dart';

enum ProviderApiStyle {
  openAICompatible,
  anthropicMessages,
  gemini,
  azureOpenAI,
  custom,
}

class ProviderCatalogEntry {
  final ProviderType type;
  final String defaultBaseUrl;
  final String defaultModel;
  final ProviderApiStyle apiStyle;
  final bool supportsBalanceQuery;
  final bool supportsModelList;
  final bool supportsUsageParsing;
  final bool supportsStreaming;
  final bool requiresCustomBaseUrl;
  final String docsUrl;
  final String noteKey;

  const ProviderCatalogEntry({
    required this.type,
    required this.defaultBaseUrl,
    required this.defaultModel,
    required this.apiStyle,
    required this.supportsBalanceQuery,
    required this.supportsModelList,
    required this.supportsUsageParsing,
    required this.supportsStreaming,
    required this.requiresCustomBaseUrl,
    required this.docsUrl,
    required this.noteKey,
  });
}

const providerCatalog = <ProviderCatalogEntry>[
  ProviderCatalogEntry(
    type: ProviderType.deepseek,
    defaultBaseUrl: 'https://api.deepseek.com',
    defaultModel: 'deepseek-chat',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: true,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://api-docs.deepseek.com/',
    noteKey: 'provider_note_deepseek',
  ),
  ProviderCatalogEntry(
    type: ProviderType.openai,
    defaultBaseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4.1-mini',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://platform.openai.com/docs/api-reference',
    noteKey: 'provider_note_openai',
  ),
  ProviderCatalogEntry(
    type: ProviderType.anthropic,
    defaultBaseUrl: 'https://api.anthropic.com/v1',
    defaultModel: 'claude-sonnet-4-5',
    apiStyle: ProviderApiStyle.anthropicMessages,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://docs.anthropic.com/en/api/overview',
    noteKey: 'provider_note_anthropic',
  ),
  ProviderCatalogEntry(
    type: ProviderType.gemini,
    defaultBaseUrl: 'https://generativelanguage.googleapis.com',
    defaultModel: 'gemini-2.5-flash',
    apiStyle: ProviderApiStyle.gemini,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    noteKey: 'provider_note_gemini',
  ),
  ProviderCatalogEntry(
    type: ProviderType.openrouter,
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'anthropic/claude-sonnet-4.5',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: true,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://openrouter.ai/docs',
    noteKey: 'provider_note_openrouter',
  ),
  ProviderCatalogEntry(
    type: ProviderType.mimo,
    defaultBaseUrl: 'https://api.xiaomimimo.com/v1',
    defaultModel: 'mimo-v2.5',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://mimo.mi.com/',
    noteKey: 'provider_note_mimo',
  ),
  ProviderCatalogEntry(
    type: ProviderType.azureOpenAI,
    defaultBaseUrl:
        'https://{resource}.openai.azure.com/openai/deployments/{deployment}',
    defaultModel: '{deployment}',
    apiStyle: ProviderApiStyle.azureOpenAI,
    supportsBalanceQuery: false,
    supportsModelList: false,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: true,
    docsUrl: 'https://learn.microsoft.com/azure/ai-services/openai/',
    noteKey: 'provider_note_azure_openai',
  ),
  ProviderCatalogEntry(
    type: ProviderType.groq,
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    defaultModel: 'openai/gpt-oss-120b',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://console.groq.com/docs/overview',
    noteKey: 'provider_note_groq',
  ),
  ProviderCatalogEntry(
    type: ProviderType.mistral,
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    defaultModel: 'mistral-medium-latest',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://docs.mistral.ai/api/',
    noteKey: 'provider_note_mistral',
  ),
  ProviderCatalogEntry(
    type: ProviderType.togetherAI,
    defaultBaseUrl: 'https://api.together.xyz/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://docs.together.ai/docs/openai-api-compatibility',
    noteKey: 'provider_note_together_ai',
  ),
  ProviderCatalogEntry(
    type: ProviderType.fireworksAI,
    defaultBaseUrl: 'https://api.fireworks.ai/inference/v1',
    defaultModel: 'accounts/fireworks/models/deepseek-v3p2',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://docs.fireworks.ai/',
    noteKey: 'provider_note_fireworks_ai',
  ),
  ProviderCatalogEntry(
    type: ProviderType.perplexity,
    defaultBaseUrl: 'https://api.perplexity.ai',
    defaultModel: 'sonar',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: false,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://docs.perplexity.ai/',
    noteKey: 'provider_note_perplexity',
  ),
  ProviderCatalogEntry(
    type: ProviderType.xai,
    defaultBaseUrl: 'https://api.x.ai/v1',
    defaultModel: 'grok-4.20',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://docs.x.ai/docs/guides/chat-completions',
    noteKey: 'provider_note_xai',
  ),
  ProviderCatalogEntry(
    type: ProviderType.cohere,
    defaultBaseUrl: 'https://api.cohere.ai/compatibility/v1',
    defaultModel: 'command-a-03-2025',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://docs.cohere.com/docs/compatibility-api',
    noteKey: 'provider_note_cohere',
  ),
  ProviderCatalogEntry(
    type: ProviderType.cerebras,
    defaultBaseUrl: 'https://api.cerebras.ai/v1',
    defaultModel: 'llama-4-scout-17b-16e-instruct',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://inference-docs.cerebras.ai/',
    noteKey: 'provider_note_cerebras',
  ),
  ProviderCatalogEntry(
    type: ProviderType.moonshot,
    defaultBaseUrl: 'https://api.moonshot.ai/v1',
    defaultModel: 'kimi-k2',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://platform.kimi.ai/docs/api/overview',
    noteKey: 'provider_note_moonshot',
  ),
  ProviderCatalogEntry(
    type: ProviderType.qwen,
    defaultBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    defaultModel: 'qwen-plus',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl:
        'https://help.aliyun.com/zh/model-studio/compatibility-of-openai-with-dashscope',
    noteKey: 'provider_note_qwen',
  ),
  ProviderCatalogEntry(
    type: ProviderType.zhipu,
    defaultBaseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    defaultModel: 'glm-4.5',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://docs.z.ai/',
    noteKey: 'provider_note_zhipu',
  ),
  ProviderCatalogEntry(
    type: ProviderType.siliconFlow,
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
    defaultModel: 'Qwen/Qwen3-235B-A22B-Instruct-2507',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://docs.siliconflow.cn/',
    noteKey: 'provider_note_silicon_flow',
  ),
  ProviderCatalogEntry(
    type: ProviderType.volcengineArk,
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    defaultModel: 'doubao-seed-1-6',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: false,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://www.volcengine.com/docs/82379',
    noteKey: 'provider_note_volcengine_ark',
  ),
  ProviderCatalogEntry(
    type: ProviderType.tencentHunyuan,
    defaultBaseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    defaultModel: 'hunyuan-turbos-latest',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://cloud.tencent.com/document/product/1729',
    noteKey: 'provider_note_tencent_hunyuan',
  ),
  ProviderCatalogEntry(
    type: ProviderType.minimax,
    defaultBaseUrl: 'https://api.minimax.io/v1',
    defaultModel: 'MiniMax-M2.7',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://platform.minimax.io/docs',
    noteKey: 'provider_note_minimax',
  ),
  ProviderCatalogEntry(
    type: ProviderType.novita,
    defaultBaseUrl: 'https://api.novita.ai/openai',
    defaultModel: 'meta-llama/llama-3.1-8b-instruct',
    apiStyle: ProviderApiStyle.openAICompatible,
    supportsBalanceQuery: false,
    supportsModelList: true,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: false,
    docsUrl: 'https://novita.ai/docs/api-reference/api-reference-overview',
    noteKey: 'provider_note_novita',
  ),
  ProviderCatalogEntry(
    type: ProviderType.customOpenAI,
    defaultBaseUrl: 'http://127.0.0.1:8000/v1',
    defaultModel: 'custom-model',
    apiStyle: ProviderApiStyle.custom,
    supportsBalanceQuery: false,
    supportsModelList: false,
    supportsUsageParsing: true,
    supportsStreaming: true,
    requiresCustomBaseUrl: true,
    docsUrl: '',
    noteKey: 'provider_note_custom_openai',
  ),
];

ProviderCatalogEntry providerCatalogFor(ProviderType type) {
  return providerCatalog.firstWhere(
    (entry) => entry.type == type,
    orElse: () => providerCatalog.last,
  );
}
